// Generated by CoffeeScript 2.4.1
(function() {
  // Copyright (c) 2019 urain39's StuffyProject.
  var _random, choice, func, global, randint, random, randrange, shuffle;

  global = this;

  // Fix namespace error.
  _random = function() {
    return Math.random();
  };

  choice = function(array) {
    var idx;
    idx = randrange(0, array.length, 1);
    return array[idx];
  };

  randint = function(min_, max_) {
    return randrange(min_, max_ + 1, 1);
  };

  randrange = function(start, stop, step) {
    var length, offset;
    if (!step) {
      step = 1;
    }
    length = Math.ceil((stop - start) / step);
    offset = Math.floor(_random() * length);
    return start + (offset * step);
  };

  shuffle = function(array, modify) {
    var arr, i, j, k, tmp;
    arr = array;
    if (!modify) {
      arr = array.slice(0, array.length);
    }
    i = 0;
    while (i < arr.length) {
      j = randint(0, arr.length);
      k = randint(0, arr.length);
      tmp = arr[j];
      arr[j] = arr[k];
      arr[k] = tmp;
      i++;
    }
    return arr;
  };

  random = {
    random: _random,
    choice: choice,
    randint: randint,
    randrange: randrange,
    shuffle: shuffle
  };

  if (typeof exports === "object") {
    for (func in random) {
      exports[func] = random[func];
    }
  } else {
    global.random = random;
  }

}).call(this);